version: "2" # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: client # specify the directory of the Dockerfile
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/angular-cli.json:/usr/src/app/angular-cli.json
      - ./client/tslint.json:/usr/src/app/tslint.json
    ports:
      - "4200:4200" # specify port forewarding

  server: #name of the second service
    build: server # specify the directory of the Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./server/tests:/usr/src/app/tests
      - ./server/src:/usr/src/app/src
      - ./server/resources:/usr/src/app/resources
      - ./server/package.json:/usr/src/app/package.json
    ports:
      - "3000:3000" #specify ports forewarding

    